
----===== # CONTRACTS (for installed and activated POS & LightPOS) - SHEET 0, dataframe 0
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1
		SELECT  c.sort,sc,
		 s.sc_symbol2, s.rok,s.week_number, COUNT(distinct contract_id) AS contract
		 FROM #channels c
		LEFT JOIN  [konkursy].[dbo].[sales_channel_details] s on sc = sales_channel2 collate Polish_CS_AI and c.rok =  s.rok and c.week = s.week_number
		WHERE c.rok = @rok  and  c.week = @ostatni_tydzien
		GROUP BY sc,s.sc_symbol2,week_number,s.rok,c.sort
		ORDER BY c.sort

---split---

----===== # POS terminals & LightPOS (installed and activated) - SHEET 0, dataframe 1

DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1



SELECT  c.sort,sc,
 s.sc_symbol2, s.rok,s.week_number, COUNT(distinct t_vid) AS POS
 FROM #channels c
LEFT JOIN  [konkursy].[dbo].[sales_channel_details] s on sc = sales_channel2 collate Polish_CS_AI and c.rok =  s.rok and c.week = s.week_number
WHERE c.rok = @rok  and  c.week = @ostatni_tydzien
GROUP BY sc,s.sc_symbol2,week_number,s.rok,c.sort
ORDER BY c.sort

---split---

----========= # LightPOS (installed and activated) - SHEET 0, dataframe 2
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1


	
SELECT  c.sort,c.sc,
 l.sales_channel2, l.rok,l.week_number, ISNULL(POS,0) as POS
 FROM #channels c
LEFT JOIN 
(select sales_channel2,rok,week_number,COUNT(distinct t_vid) AS POS
FROM
[konkursy].[dbo].[sales_channel_details] 
WHERE rok = @rok and week_number = @ostatni_tydzien
		and lightpos = 'lightpos'
GROUP BY sales_channel2,rok,week_number) as l on l.sales_channel2 = c.sc collate Polish_CI_AS
ORDER BY sort

---split---

----======= # # transactions (ePay) all merchants POS & LightPOS - SHEET 1, dataframe 3
		-- #transactions ePay allmerchants
		-- w PBI - qty_txn
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1



SELECT   c.sort,sc,
 s.sc_symbol2, s.rok,s.week_number, SUM(qty) AS qty
 FROM #channels c
LEFT JOIN [konkursy].[dbo].[sales_channel_trans_details] s on c.sc = s.sales_channel2 collate Polish_CI_AS and c.rok = s.rok and c.week = s.week_number
WHERE c.rok = @rok  and  c.week = @ostatni_tydzien
GROUP BY sc,s.sc_symbol2,week_number,s.rok,c.sort
ORDER BY c.sort

---split---

-----=======  # transactions (ePay) all merchants LightPOS  - SHEET 1, dataframe 4
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1
		
		
		
SELECT  c.sort,c.sc,
 l.sales_channel2, l.rok,l.week_number,  ISNULL(qty,0) as qty
 FROM #channels c
LEFT JOIN 
(select sales_channel2,rok,week_number,SUM(qty) as  qty
FROM
[konkursy].[dbo].[sales_channel_trans_details] 
WHERE rok = @rok and week_number = @ostatni_tydzien
		and lightpos = 'lightpos'
GROUP BY sales_channel2,rok,week_number) as l on l.sales_channel2 = c.sc collate Polish_CI_AS
ORDER BY sort

---split---

----======= Σ value transactions (ePay) all merchants POS & LightPOS - SHEET 1, dataframe 5
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1



SELECT   c.sort,sc,
 s.sc_symbol2, s.rok,s.week_number, SUM(cast(value as money))/100 AS value
 FROM #channels c
LEFT JOIN [konkursy].[dbo].[sales_channel_trans_details] s on c.sc = s.sales_channel2 collate Polish_CI_AS and c.rok = s.rok and c.week = s.week_number
WHERE c.rok = @rok  and  c.week = @ostatni_tydzien
GROUP BY sc,s.sc_symbol2,week_number,s.rok,c.sort
ORDER BY c.sort

---split---

-----======= Σ value transactions (ePay) all merchants LightPOS  - SHEET 1, dataframe 6
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1
		
		
		

SELECT  c.sort,c.sc,
 l.sales_channel2, l.rok,l.week_number,  ISNULL(value,0) as value
 FROM #channels c
LEFT JOIN 
(select sales_channel2,rok,week_number,SUM(cast(value as money))/100 AS value
FROM
[konkursy].[dbo].[sales_channel_trans_details] 
WHERE rok = @rok and week_number = @ostatni_tydzien
		and lightpos = 'lightpos'
GROUP BY sales_channel2,rok,week_number) as l on l.sales_channel2 = c.sc collate Polish_CI_AS
ORDER BY sort

---split---

-----===============================================================================
----Σ value (cumulatively) transactions (ePay) generated by POS & LightPOS acquired since the beginning of the year  - SHEET 1, dataframe 7

select 
c.sort,c.sc,sales_channel2,ISNULL(SUM(val),0) as value 
from #channels c
left join #t11 t on c.sc = t.sales_channel2 collate Polish_CS_AI
group by c.sort,c.sc,sales_channel2
order by c.sort

---split---

-----===================================================================================================================================
----- Σ value (cumulatively) transactions (ePay) generated by LightPOS acquired since the beginning of the year - SHEET 1, dataframe 8

select 
c.sort,c.sc,sales_channel2,ISNULL(SUM(val),0) as value 
from #channels c
left join #t1 t on c.sc = t.sales_channel2 collate Polish_CS_AI
group by c.sort,c.sc,sales_channel2
order by c.sort

---split---

---- Σ value transactions (ePay) of last week generated by POS & LightPOS acquired since the beginning of the year - SHEET 1, dataframe 9
--- transakcje z last week dla POS  pozyskanych w 2021-------------------------

select 
c.sort,c.sc,sales_channel2,ISNULL(SUM(val),0) as value 
from #channels c
left join #t2 t on c.sc = t.sales_channel2 collate Polish_CS_AI
group by c.sort,c.sc,sales_channel2
order by c.sort

---split---

----===============================================================================================================================================
---- Σ value transactions (ePay) of last week generated by LightPOS acquired since the beginning of the year  - SHEET 1, dataframe 10

select 
c.sort,c.sc,sales_channel2,ISNULL(SUM(val),0) as value 
from #channels c
left join #t22 t on c.sc = t.sales_channel2 collate Polish_CS_AI
group by c.sort,c.sc,sales_channel2
order by c.sort

---split---

----==============================================================================================================================================
---- Σ value transactions (ePay) of last week generated by POS & LightPOS acquired in previous month  - SHEET 1, dataframe 11

select 
c.sort,c.sc,sales_channel2,ISNULL(SUM(val),0) as value 
from #channels c
left join #t3_1 t on c.sc = t.sales_channel2 collate Polish_CS_AI
left join #t3_2 on tr_tvid=t_vid Collate Polish_CS_AI
group by c.sort,c.sc,t.sales_channel2
order by c.sort

---split---

----==============================================================================================================================================
---- Σ value transactions (ePay) of last week generated by LightPOS acquired in previous month  - SHEET 1, dataframe 12

select 
c.sort,c.sc,sales_channel2,ISNULL(SUM(val),0) as value 
from #channels c
left join #t3_11 t on c.sc = t.sales_channel2 collate Polish_CS_AI
left join #t3_22 on tr_tvid=t_vid Collate Polish_CS_AI
group by c.sort,c.sc,t.sales_channel2
order by c.sort

---split---

----==============================================================================================================================================
---- AVG turnover/POS & LightPOS (ePay)  for all merchants  - SHEET 1, dataframe 13

select 
c.sort,c.sc,a.sales_channel2,a.week_number,a.rok ,
SUM(value)/SUM(POS)  as avg_turnover
from 
#channels c 
left join #av a on c.sc = a.sales_channel2 collate Polish_CS_AI and c.week = a.week_number and c.rok = a.rok
group by c.sort,c.sc,a.sales_channel2,a.week_number,a.rok 
order by c.sort

---split---

----==============================================================================================================================================
---- AVG turnover/ LightPOS (ePay)  for all merchants  - SHEET 1, dataframe 14

select 
c.sort,c.sc,a.sales_channel2,a.week_number,a.rok ,
ISNULL(SUM(value)/SUM(POS),0)  as avg_turnover
from 
#channels c 
left join #av1 a on c.sc = a.sales_channel2 collate Polish_CS_AI and c.week = a.week_number and c.rok = a.rok
group by c.sort,c.sc,a.sales_channel2,a.week_number,a.rok 
order by c.sort

---split---

----==============================================================================================================================================
---- AVG time (days) between activation date and first transaction POS & LightPOS  - SHEET 1, dataframe 17
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1

select  
 c.sort,c.sc,sales_channel2,d.rok,
week_number, 
AVG(cast(days_diff as money)) as AVG_days_first_transaction
--count(*) - count(days_diff) as number_of_null,
--count(days_diff) as number_of_tvid_transaction
FROM 
#channels c
LEFT JOIN [konkursy].[dbo].[sales_channel_details] d on c.sc = d.sales_channel2 collate Polish_CS_AI and c.rok = d.rok and c.week = d.week_number
where c.rok>=@rok and c.week=@ostatni_tydzien
group by  c.sort,c.sc,sales_channel2,d.rok,
week_number
order by c.sort

---split---

----==============================================================================================================================================
---- AVG time (days) between activation date and first transaction  LightPOS  - SHEET 1, dataframe 18
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1

select  
 c.sort,c.sc,sales_channel2,d.rok,
d.week_number, 
 AVG_days_first_transaction
--count(*) - count(days_diff) as number_of_null,
--count(days_diff) as number_of_tvid_transaction
FROM 
#channels c
LEFT JOIN ( SELECT rok,week_number,sales_channel2,AVG(cast(days_diff as money)) as AVG_days_first_transaction
from [konkursy].[dbo].[sales_channel_details] 
where rok=@rok and week_number=@ostatni_tydzien and lightpos='lightpos'
group by rok,week_number,sales_channel2) as d on  d.sales_channel2 = c.sc collate Polish_CI_AS
order by c.sort

---split---

----==============================================================================================================================================
---- # POS & LightPOS with transactions according to week of activation  - SHEET 1, dataframe 19
DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1

select  
 c.sort,c.sc,sales_channel2,d.rok,
week_number, 
--AVG(cast(days_diff as money)) as AVG_days_first_transaction,
--count(*) - count(days_diff) as number_of_null,
count(days_diff) as number_of_tvid_transaction
FROM 
#channels c
LEFT JOIN [konkursy].[dbo].[sales_channel_details] d on c.sc = d.sales_channel2 collate Polish_CS_AI and c.rok = d.rok and c.week = d.week_number
where c.rok>=@rok and c.week=@ostatni_tydzien
group by  c.sort,c.sc,sales_channel2,d.rok,
week_number
order by c.sort

---split---

----==============================================================================================================================================
---- #LightPOS with transactions according to week of activation  - SHEET 1, dataframe 20

DECLARE @ostatni_tydzien AS int
DECLARE @rok AS int
SET @rok = YEAR(DATEADD(ww, -1,getdate()))
SET @ostatni_tydzien = datename(ww, getdate())-1

select  
 c.sort,c.sc,sales_channel2,d.rok,
d.week_number, 
-- AVG_days_first_transaction
--count(*) - count(days_diff) as number_of_null,
 number_of_tvid_transaction
FROM 
#channels c
LEFT JOIN ( SELECT rok,week_number,sales_channel2,count(days_diff) as number_of_tvid_transaction
from [konkursy].[dbo].[sales_channel_details] 
where rok=@rok and week_number=@ostatni_tydzien and lightpos='lightpos'
group by rok,week_number,sales_channel2) as d on  d.sales_channel2 = c.sc collate Polish_CI_AS
order by c.sort
