name: pyinstaller - Build and Publish v2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd ../

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller
        
      - name: Install pyodbc
        run: pip install pyodbc
        
      - name: Build executable
        run: pyinstaller --onefile --name Weekly_Sales_Channel_Report --icon=weekly_sales_automate/UI/logos/icon.ico weekly_sales_automate/ui.py

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: Weekly_Sales_Channel_Report
          path: dist/Weekly_Sales_Channel_Report.exe
